// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Data;

#nullable disable

namespace PetStore.Migrations
{
    [DbContext(typeof(PetStoreContext))]
    [Migration("20260402064739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetStore.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PetStore.Pet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Adopt")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Foster")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Friendly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Shelter_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Breed = "Golden Retriever",
                            Description = "Friendly, loyal, and ready for a home.",
                            Energy = 4,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/goldenr.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Max",
                            Shelter_id = "SHELTER-01",
                            Type = "dogs",
                            YearOfBirth = 2021
                        },
                        new
                        {
                            Id = "2",
                            Breed = "Siamese",
                            Description = "Curious, calm, and full of personality.",
                            Energy = 3,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/siamese.jpg",
                            Is_Adopt = true,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Luna",
                            Shelter_id = "SHELTER-01",
                            Type = "cats",
                            YearOfBirth = 2022
                        },
                        new
                        {
                            Id = "3",
                            Breed = "Mini Flame",
                            Description = "Magical companion with fiery charm.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/toothless.jpg",
                            Is_Adopt = false,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Toothless",
                            Shelter_id = "SHELTER-02",
                            Type = "dragons",
                            YearOfBirth = 2010
                        },
                        new
                        {
                            Id = "4",
                            Breed = "Silver Mane",
                            Description = "Rare, graceful, and full of wonder.",
                            Energy = 2,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/unicorn.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Sparkle",
                            Shelter_id = "SHELTER-02",
                            Type = "unicorns",
                            YearOfBirth = 2019
                        },
                        new
                        {
                            Id = "5",
                            Breed = "Maltese",
                            Description = "Intelligent and handsome. He just loves to be with you.",
                            Energy = 3,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/maltese.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Cloud",
                            Shelter_id = "SHELTER-01",
                            Type = "dogs",
                            YearOfBirth = 2023
                        },
                        new
                        {
                            Id = "6",
                            Breed = "Asian Elephant",
                            Description = "Curious, adorable, and intelligent.",
                            Energy = 2,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/elephant.jpg",
                            Is_Adopt = false,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Jimbo",
                            Shelter_id = "SHELTER-03",
                            Type = "elephants",
                            YearOfBirth = 2020
                        },
                        new
                        {
                            Id = "7",
                            Breed = "Siberian Tiger",
                            Description = "Majestic, regal, and content. All she wants is to bathe.",
                            Energy = 1,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/tiger.jpg",
                            Is_Adopt = false,
                            Is_Foster = false,
                            Is_Friendly = false,
                            Name = "Raja",
                            Shelter_id = "SHELTER-03",
                            Type = "cats",
                            YearOfBirth = 2017
                        },
                        new
                        {
                            Id = "8",
                            Breed = "White Cockatoo",
                            Description = "Loves to talk, sing, and dance.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/white-parrot.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Marshmallow",
                            Shelter_id = "SHELTER-01",
                            Type = "birds",
                            YearOfBirth = 2014
                        });
                });

            modelBuilder.Entity("PetStore.PetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "dogs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "cats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "dragons"
                        },
                        new
                        {
                            Id = 4,
                            Name = "unicorns"
                        },
                        new
                        {
                            Id = 5,
                            Name = "birds"
                        },
                        new
                        {
                            Id = 6,
                            Name = "elephants"
                        });
                });

            modelBuilder.Entity("PetStore.Shelter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = "SHELTER-01",
                            Country = "US",
                            Email = "contact@goldenpawsrescue.org",
                            Name = "Golden Paws Rescue",
                            State = "Pennsylvania",
                            User_id = "user_01"
                        },
                        new
                        {
                            Id = "SHELTER-02",
                            Country = "CA",
                            Email = "hello@whiskerhaven.org",
                            Name = "Whisker Haven",
                            State = "Ontario",
                            User_id = "user_02"
                        },
                        new
                        {
                            Id = "SHELTER-03",
                            Country = "AU",
                            Email = "info@safewingssanctuary.org",
                            Name = "Safe Wings Sanctuary",
                            State = "New South Wales",
                            User_id = "user_03"
                        },
                        new
                        {
                            Id = "SHELTER-04",
                            Country = "VE",
                            Email = "support@cloudinthesky.org",
                            Name = "Cloud in the Sky",
                            State = "Mérida",
                            User_id = "user_04"
                        },
                        new
                        {
                            Id = "SHELTER-05",
                            Country = "ZA",
                            Email = "team@wildheartrefuge.org",
                            Name = "Wild Heart Refuge",
                            State = "Western Cape",
                            User_id = "user_05"
                        },
                        new
                        {
                            Id = "SHELTER-06",
                            Country = "MX",
                            Email = "care@hopetailsshelter.org",
                            Name = "Hope Tails Shelter",
                            State = "Guanajuato",
                            User_id = "user_06"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PetStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PetStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PetStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
