namespace PetStore.Services;

public class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> translations = new()
    {
        ["English"] = new()
        {
            ["Language"] = "Language",
            ["Home"] = "Home",
            ["Shelters"] = "Shelters",
            ["AboutUs"] = "About Us",
            ["UpdateAnimals"] = "Update Animals",
            ["SignIn"] = "Sign In",
            ["LogOut"] = "Log Out",
            ["Hello"] = "Hello",
            ["HomeTitle"] = "Pawsitive Friends | Home",
            ["HomeHeroTitlePrefix"] = "Search to find your",
            ["HomeHeroTitleHighlight"] = "new best friend.",
            ["HomeHeroDescription"] = "Connecting loving families with pets in need. Start by selecting a shelter near you.",
            ["Adopt"] = "Adopt",
            ["Donate"] = "Donate",
            ["Volunteer"] = "Volunteer",
            ["ViewPets"] = "View Pets",
            ["GiveToday"] = "Give Today",
            ["JoinUs"] = "Join Us",
            ["AdoptCardDescription"] = "Find your perfect match and give a pet a forever home.",
            ["DonateCardDescription"] = "Support our mission with food, medicine, and shelter.",
            ["VolunteerCardDescription"] = "Share your time and love with animals in need.",
            ["ShowingPetsForShelter"] = "Showing pets for shelter ID:",
            ["OurMission"] = "Our Mission",
            ["MissionDescription"] = "Every animal deserves a safe place to call home. We partner with local shelters to provide care and find forever families, ensuring every tail finds its happy ending.",
            ["FooterBrandDescription"] = "Helping pets find safety, care, and loving homes through shelters, volunteers, and community support.",
            ["Links"] = "Links",
            ["About"] = "About",
            ["Pets"] = "Pets",
            ["ContactUs"] = "Contact Us",
            ["Hours"] = "Mon - Sat, 9:00 AM - 6:00 PM",
            ["TermsAndConditions"] = "Terms & Conditions",
            ["TermsText"] = "By using this site, you agree to provide accurate information, respect adoption procedures, and use our services responsibly.",
            ["AllRightsReserved"] = "All rights reserved.",
            ["AboutPageTitle"] = "About Us",
            ["AboutHeading"] = "About Pawsitive Friends",
            ["AboutText"] = "We are a non-profit organization that has partnered with shelters worldwide to bring attention to animals in need of love, care, and a forever home. Our mission is to connect people with shelters and help shine a light on animals waiting for a second chance.",
            ["DonatePageTitle"] = "Donate | Pawsitive Friends",
            ["SupportOurMission"] = "Support Our Mission",
            ["DonateHeading"] = "Help us care for more pets.",
            ["KindlyContactUsOn"] = "Kindly contact us on",
            ["OrFillFormContact"] = "Or fill out the form so we can contact you.",
            ["DonateSuccess"] = "We will contact you as soon as we receive your details.",
            ["FirstName"] = "First Name",
            ["LastName"] = "Last Name",
            ["Country"] = "Country",
            ["SelectCountry"] = "Select a country",
            ["PhoneNumber"] = "Phone Number",
            ["Email"] = "Email",
            ["Submit"] = "Submit",
            ["ReachUsThrough"] = "Or reach us through:",
            ["VolunteerPageTitle"] = "Join Our Volunteer Team",
            ["JoinTheCrew"] = "Join The Crew",
            ["VolunteerHeading"] = "Share your time, care, and energy with rescued pets.",
            ["VolunteerLead"] = "Volunteer with us and help create safer, happier days for pets waiting for a home.",
            ["VolunteerSupport"] = "Fill out the form and our team will reach out with the next steps.",
            ["VolunteerSuccess"] = "Thank you for your interest in volunteering. We'll contact you as soon as we receive your details.",
            ["SubmitApplication"] = "Submit Application",
            ["SigninHeading"] = "Sign In",
            ["SigninText"] = "Please sign in to help your Pawsitive Friend!",
            ["ContinueWithGoogle"] = "Continue with Google",
            ["ApplicationPageTitle"] = "Pet Application",
            ["PetApplication"] = "Pet Application",
            ["PersonalInformation"] = "Personal Information",
            ["FullName"] = "Full Name",
            ["Address"] = "Address",
            ["HowWouldYouLikeToHelp"] = "How Would You Like To Help?",
            ["Foster"] = "Foster",
            ["Sponsor"] = "Sponsor",
            ["AdoptionQuestions"] = "Adoption Questions",
            ["DoYouOwnOrRent"] = "Do you own or rent?",
            ["DoYouHaveOtherPets"] = "Do you have other pets?",
            ["WhyDoYouWantToAdopt"] = "Why do you want to adopt?",
            ["FosterQuestions"] = "Foster Questions",
            ["HowLongCanYouFoster"] = "How long can you foster?",
            ["ExperienceWithAnimals"] = "Experience with animals?",
            ["SponsorshipQuestions"] = "Sponsorship Questions",
            ["MonthlyContribution"] = "Monthly contribution",
            ["WhyDoYouWantToSponsor"] = "Why do you want to sponsor?",
            ["ConfirmAccurate"] = "I confirm all information is accurate",
            ["NoPetNameProvided"] = "No pet name provided"
            ,
            ["FindNearestShelter"] = "FIND YOUR NEAREST SHELTER",
            ["ChooseLocation"] = "-- Choose a location --",
            ["SeeAllPets"] = "See all pets",
            ["SelectAShelter"] = "Select a shelter",
            ["GoToShelter"] = "Go to {0}",
            ["PetsPageTitle"] = "Pets",
            ["All"] = "All",
            ["NoPetsInCategory"] = "No pets found in this category.",
            ["Age"] = "Age",
            ["LessThanYearOld"] = "Less than a year old",
            ["YearOld"] = "{0} year old",
            ["YearsOld"] = "{0} years old",
            ["Breed"] = "Breed",
            ["Energy"] = "Energy",
            ["Description"] = "Description",
            ["HelpPet"] = "Help {0}",
            ["ThankYouPageTitle"] = "Thank You {0}",
            ["ThankYou"] = "Thank You!",
            ["ApplicationNotFound"] = "We could not find your application.",
            ["ThankYouName"] = "Thank you, {0}!",
            ["ApplicationReceived"] = "We have successfully received your application to {0}. We will review your application and reach out to you within 7 to 10 business days.",
            ["ApplicationId"] = "Application ID",
            ["Submitted"] = "Submitted",
            ["ReturnHome"] = "Return to Home",
            ["NotFound"] = "Not Found",
            ["NotFoundText"] = "Sorry, the content you are looking for does not exist."
        },
        ["Spanish"] = new()
        {
            ["Language"] = "Idioma",
            ["Home"] = "Inicio",
            ["Shelters"] = "Refugios",
            ["AboutUs"] = "Acerca de",
            ["UpdateAnimals"] = "Actualizar animales",
            ["SignIn"] = "Iniciar sesión",
            ["LogOut"] = "Cerrar sesión",
            ["Hello"] = "Hola",
            ["HomeTitle"] = "Pawsitive Friends | Inicio",
            ["HomeHeroTitlePrefix"] = "Busca para encontrar a tu",
            ["HomeHeroTitleHighlight"] = "nuevo mejor amigo.",
            ["HomeHeroDescription"] = "Conectamos familias amorosas con mascotas que lo necesitan. Comienza seleccionando un refugio cercano.",
            ["Adopt"] = "Adoptar",
            ["Donate"] = "Donar",
            ["Volunteer"] = "Ser voluntario",
            ["ViewPets"] = "Ver mascotas",
            ["GiveToday"] = "Dona hoy",
            ["JoinUs"] = "Únete",
            ["AdoptCardDescription"] = "Encuentra a tu compañero ideal y dale a una mascota un hogar para siempre.",
            ["DonateCardDescription"] = "Apoya nuestra misión con comida, medicina y refugio.",
            ["VolunteerCardDescription"] = "Comparte tu tiempo y amor con animales que lo necesitan.",
            ["ShowingPetsForShelter"] = "Mostrando mascotas para el refugio con ID:",
            ["OurMission"] = "Nuestra misión",
            ["MissionDescription"] = "Cada animal merece un lugar seguro al que llamar hogar. Nos asociamos con refugios locales para brindar cuidado y encontrar familias para siempre, asegurando que cada cola tenga un final feliz.",
            ["FooterBrandDescription"] = "Ayudamos a las mascotas a encontrar seguridad, cuidado y hogares amorosos mediante refugios, voluntarios y apoyo comunitario.",
            ["Links"] = "Enlaces",
            ["About"] = "Acerca de",
            ["Pets"] = "Mascotas",
            ["ContactUs"] = "Contáctanos",
            ["Hours"] = "Lun - Sáb, 9:00 AM - 6:00 PM",
            ["TermsAndConditions"] = "Términos y condiciones",
            ["TermsText"] = "Al usar este sitio, aceptas proporcionar información precisa, respetar los procedimientos de adopción y usar nuestros servicios responsablemente.",
            ["AllRightsReserved"] = "Todos los derechos reservados.",
            ["AboutPageTitle"] = "Sobre nosotros",
            ["AboutHeading"] = "Sobre Pawsitive Friends",
            ["AboutText"] = "Somos una organización sin fines de lucro que se ha asociado con refugios de todo el mundo para llamar la atención sobre animales que necesitan amor, cuidado y un hogar para siempre. Nuestra misión es conectar a las personas con refugios y ayudar a iluminar la vida de animales que esperan una segunda oportunidad.",
            ["DonatePageTitle"] = "Donar | Pawsitive Friends",
            ["SupportOurMission"] = "Apoya nuestra misión",
            ["DonateHeading"] = "Ayúdanos a cuidar a más mascotas.",
            ["KindlyContactUsOn"] = "Por favor contáctanos en",
            ["OrFillFormContact"] = "O completa el formulario para que podamos contactarte.",
            ["DonateSuccess"] = "Nos pondremos en contacto contigo tan pronto como recibamos tus datos.",
            ["FirstName"] = "Nombre",
            ["LastName"] = "Apellido",
            ["Country"] = "País",
            ["SelectCountry"] = "Selecciona un país",
            ["PhoneNumber"] = "Número de teléfono",
            ["Email"] = "Correo electrónico",
            ["Submit"] = "Enviar",
            ["ReachUsThrough"] = "O contáctanos por:",
            ["VolunteerPageTitle"] = "Únete a nuestro equipo de voluntarios",
            ["JoinTheCrew"] = "Únete al equipo",
            ["VolunteerHeading"] = "Comparte tu tiempo, cuidado y energía con mascotas rescatadas.",
            ["VolunteerLead"] = "Haz voluntariado con nosotros y ayuda a crear días más seguros y felices para mascotas que esperan un hogar.",
            ["VolunteerSupport"] = "Completa el formulario y nuestro equipo se pondrá en contacto contigo con los siguientes pasos.",
            ["VolunteerSuccess"] = "Gracias por tu interés en ser voluntario. Te contactaremos tan pronto como recibamos tus datos.",
            ["SubmitApplication"] = "Enviar solicitud",
            ["SigninHeading"] = "Iniciar sesión",
            ["SigninText"] = "Inicia sesión para ayudar a tu amigo de Pawsitive.",
            ["ContinueWithGoogle"] = "Continuar con Google",
            ["ApplicationPageTitle"] = "Solicitud para mascota",
            ["PetApplication"] = "Solicitud para mascota",
            ["PersonalInformation"] = "Información personal",
            ["FullName"] = "Nombre completo",
            ["Address"] = "Dirección",
            ["HowWouldYouLikeToHelp"] = "¿Cómo te gustaría ayudar?",
            ["Foster"] = "Acoger",
            ["Sponsor"] = "Patrocinar",
            ["AdoptionQuestions"] = "Preguntas de adopción",
            ["DoYouOwnOrRent"] = "¿Eres propietario o alquilas?",
            ["DoYouHaveOtherPets"] = "¿Tienes otras mascotas?",
            ["WhyDoYouWantToAdopt"] = "¿Por qué quieres adoptar?",
            ["FosterQuestions"] = "Preguntas sobre acogida",
            ["HowLongCanYouFoster"] = "¿Cuánto tiempo puedes acoger?",
            ["ExperienceWithAnimals"] = "¿Experiencia con animales?",
            ["SponsorshipQuestions"] = "Preguntas sobre patrocinio",
            ["MonthlyContribution"] = "Contribución mensual",
            ["WhyDoYouWantToSponsor"] = "¿Por qué quieres patrocinar?",
            ["ConfirmAccurate"] = "Confirmo que toda la información es correcta",
            ["NoPetNameProvided"] = "No se proporcionó nombre de mascota",
            ["FindNearestShelter"] = "ENCUENTRA TU REFUGIO MÁS CERCANO",
            ["ChooseLocation"] = "-- Elige una ubicación --",
            ["SeeAllPets"] = "Ver todas las mascotas",
            ["SelectAShelter"] = "Selecciona un refugio",
            ["GoToShelter"] = "Ir a {0}",
            ["PetsPageTitle"] = "Mascotas",
            ["All"] = "Todas",
            ["NoPetsInCategory"] = "No se encontraron mascotas en esta categoría.",
            ["Age"] = "Edad",
            ["LessThanYearOld"] = "Menos de un año",
            ["YearOld"] = "{0} año",
            ["YearsOld"] = "{0} años",
            ["Breed"] = "Raza",
            ["Energy"] = "Energía",
            ["Description"] = "Descripción",
            ["HelpPet"] = "Ayudar a {0}",
            ["ThankYouPageTitle"] = "Gracias {0}",
            ["ThankYou"] = "¡Gracias!",
            ["ApplicationNotFound"] = "No pudimos encontrar tu solicitud.",
            ["ThankYouName"] = "Gracias, {0}!",
            ["ApplicationReceived"] = "Hemos recibido con éxito tu solicitud para {0}. Revisaremos tu solicitud y nos pondremos en contacto contigo en un plazo de 7 a 10 días hábiles.",
            ["ApplicationId"] = "ID de solicitud",
            ["Submitted"] = "Enviado",
            ["ReturnHome"] = "Volver al inicio",
            ["NotFound"] = "No encontrado",
            ["NotFoundText"] = "Lo sentimos, el contenido que buscas no existe."
        },
        ["French"] = new()
        {
            ["Language"] = "Langue",
            ["Home"] = "Accueil",
            ["Shelters"] = "Refuges",
            ["AboutUs"] = "À propos",
            ["UpdateAnimals"] = "Mettre à jour les animaux",
            ["SignIn"] = "Se connecter",
            ["LogOut"] = "Se déconnecter",
            ["Hello"] = "Bonjour",
            ["HomeTitle"] = "Pawsitive Friends | Accueil",
            ["HomeHeroTitlePrefix"] = "Cherchez pour trouver votre",
            ["HomeHeroTitleHighlight"] = "nouveau meilleur ami.",
            ["HomeHeroDescription"] = "Nous mettons en relation des familles aimantes avec des animaux qui en ont besoin. Commencez par sélectionner un refuge près de chez vous.",
            ["Adopt"] = "Adopter",
            ["Donate"] = "Faire un don",
            ["Volunteer"] = "Bénévole",
            ["ViewPets"] = "Voir les animaux",
            ["GiveToday"] = "Donner aujourd'hui",
            ["JoinUs"] = "Rejoignez-nous",
            ["AdoptCardDescription"] = "Trouvez votre compagnon idéal et offrez à un animal un foyer pour toujours.",
            ["DonateCardDescription"] = "Soutenez notre mission avec de la nourriture, des médicaments et un abri.",
            ["VolunteerCardDescription"] = "Offrez votre temps et votre amour aux animaux dans le besoin.",
            ["ShowingPetsForShelter"] = "Animaux affichés pour le refuge ID :",
            ["OurMission"] = "Notre mission",
            ["MissionDescription"] = "Chaque animal mérite un endroit sûr où vivre. Nous collaborons avec des refuges locaux pour apporter des soins et trouver des familles pour toujours, afin que chaque queue connaisse une fin heureuse.",
            ["FooterBrandDescription"] = "Nous aidons les animaux à trouver sécurité, soins et foyers aimants grâce aux refuges, aux bénévoles et au soutien de la communauté.",
            ["Links"] = "Liens",
            ["About"] = "À propos",
            ["Pets"] = "Animaux",
            ["ContactUs"] = "Contactez-nous",
            ["Hours"] = "Lun - Sam, 9h00 - 18h00",
            ["TermsAndConditions"] = "Conditions générales",
            ["TermsText"] = "En utilisant ce site, vous acceptez de fournir des informations exactes, de respecter les procédures d'adoption et d'utiliser nos services de manière responsable.",
            ["AllRightsReserved"] = "Tous droits réservés.",
            ["AboutPageTitle"] = "À propos de nous",
            ["AboutHeading"] = "À propos de Pawsitive Friends",
            ["AboutText"] = "Nous sommes une organisation à but non lucratif qui s'est associée à des refuges dans le monde entier pour attirer l'attention sur les animaux ayant besoin d'amour, de soins et d'un foyer pour toujours. Notre mission est de mettre les personnes en relation avec les refuges et de donner une seconde chance aux animaux qui attendent.",
            ["DonatePageTitle"] = "Don | Pawsitive Friends",
            ["SupportOurMission"] = "Soutenez notre mission",
            ["DonateHeading"] = "Aidez-nous à prendre soin de plus d'animaux de compagnie.",
            ["KindlyContactUsOn"] = "Veuillez nous contacter au",
            ["OrFillFormContact"] = "Ou remplissez le formulaire afin que nous puissions vous contacter.",
            ["DonateSuccess"] = "Nous vous contacterons dès que nous aurons reçu vos informations.",
            ["FirstName"] = "Prénom",
            ["LastName"] = "Nom",
            ["Country"] = "Pays",
            ["SelectCountry"] = "Sélectionnez un pays",
            ["PhoneNumber"] = "Numéro de téléphone",
            ["Email"] = "E-mail",
            ["Submit"] = "Soumettre",
            ["ReachUsThrough"] = "Ou contactez-nous via :",
            ["VolunteerPageTitle"] = "Rejoignez notre équipe de bénévoles",
            ["JoinTheCrew"] = "Rejoignez l'équipe",
            ["VolunteerHeading"] = "Partagez votre temps, votre attention et votre énergie avec des animaux secourus.",
            ["VolunteerLead"] = "Faites du bénévolat avec nous et contribuez à rendre les journées plus sûres et plus heureuses pour les animaux qui attendent un foyer.",
            ["VolunteerSupport"] = "Remplissez le formulaire et notre équipe vous contactera pour les prochaines étapes.",
            ["VolunteerSuccess"] = "Merci pour votre intérêt pour le bénévolat. Nous vous contacterons dès réception de vos informations.",
            ["SubmitApplication"] = "Soumettre la demande",
            ["SigninHeading"] = "Se connecter",
            ["SigninText"] = "Veuillez vous connecter pour aider votre ami Pawsitive !",
            ["ContinueWithGoogle"] = "Continuer avec Google",
            ["ApplicationPageTitle"] = "Demande pour un animal",
            ["PetApplication"] = "Demande pour un animal",
            ["PersonalInformation"] = "Informations personnelles",
            ["FullName"] = "Nom complet",
            ["Address"] = "Adresse",
            ["HowWouldYouLikeToHelp"] = "Comment souhaitez-vous aider ?",
            ["Foster"] = "Accueillir",
            ["Sponsor"] = "Parrainer",
            ["AdoptionQuestions"] = "Questions d'adoption",
            ["DoYouOwnOrRent"] = "Êtes-vous propriétaire ou locataire ?",
            ["DoYouHaveOtherPets"] = "Avez-vous d'autres animaux ?",
            ["WhyDoYouWantToAdopt"] = "Pourquoi voulez-vous adopter ?",
            ["FosterQuestions"] = "Questions d'accueil",
            ["HowLongCanYouFoster"] = "Combien de temps pouvez-vous accueillir ?",
            ["ExperienceWithAnimals"] = "Expérience avec les animaux ?",
            ["SponsorshipQuestions"] = "Questions sur le parrainage",
            ["MonthlyContribution"] = "Contribution mensuelle",
            ["WhyDoYouWantToSponsor"] = "Pourquoi voulez-vous parrainer ?",
            ["ConfirmAccurate"] = "Je confirme que toutes les informations sont exactes",
            ["NoPetNameProvided"] = "Aucun nom d'animal fourni",
            ["FindNearestShelter"] = "TROUVEZ LE REFUGE LE PLUS PROCHE",
            ["ChooseLocation"] = "-- Choisissez un lieu --",
            ["SeeAllPets"] = "Voir tous les animaux",
            ["SelectAShelter"] = "Sélectionnez un refuge",
            ["GoToShelter"] = "Aller à {0}",
            ["PetsPageTitle"] = "Animaux",
            ["All"] = "Tous",
            ["NoPetsInCategory"] = "Aucun animal trouvé dans cette catégorie.",
            ["Age"] = "Âge",
            ["LessThanYearOld"] = "Moins d'un an",
            ["YearOld"] = "{0} an",
            ["YearsOld"] = "{0} ans",
            ["Breed"] = "Race",
            ["Energy"] = "Énergie",
            ["Description"] = "Description",
            ["HelpPet"] = "Aider {0}",
            ["ThankYouPageTitle"] = "Merci {0}",
            ["ThankYou"] = "Merci !",
            ["ApplicationNotFound"] = "Nous n'avons pas pu trouver votre demande.",
            ["ThankYouName"] = "Merci, {0} !",
            ["ApplicationReceived"] = "Nous avons bien reçu votre demande pour {0}. Nous examinerons votre demande et vous contacterons dans un délai de 7 à 10 jours ouvrables.",
            ["ApplicationId"] = "ID de la demande",
            ["Submitted"] = "Soumis",
            ["ReturnHome"] = "Retour à l'accueil",
            ["NotFound"] = "Introuvable",
            ["NotFoundText"] = "Désolé, le contenu que vous recherchez n'existe pas."
        },
        ["Portuguese"] = new()
        {
            ["Language"] = "Idioma",
            ["Home"] = "Início",
            ["Shelters"] = "Abrigos",
            ["AboutUs"] = "Sobre nós",
            ["UpdateAnimals"] = "Atualizar animais",
            ["SignIn"] = "Entrar",
            ["LogOut"] = "Sair",
            ["Hello"] = "Olá",
            ["HomeTitle"] = "Pawsitive Friends | Início",
            ["HomeHeroTitlePrefix"] = "Procure para encontrar seu",
            ["HomeHeroTitleHighlight"] = "novo melhor amigo.",
            ["HomeHeroDescription"] = "Conectamos famílias amorosas com pets que precisam de ajuda. Comece selecionando um abrigo perto de você.",
            ["Adopt"] = "Adotar",
            ["Donate"] = "Doar",
            ["Volunteer"] = "Voluntário",
            ["ViewPets"] = "Ver pets",
            ["GiveToday"] = "Doe hoje",
            ["JoinUs"] = "Junte-se a nós",
            ["AdoptCardDescription"] = "Encontre o seu par perfeito e dê a um pet um lar para sempre.",
            ["DonateCardDescription"] = "Apoie nossa missão com comida, remédios e abrigo.",
            ["VolunteerCardDescription"] = "Compartilhe seu tempo e amor com animais necessitados.",
            ["ShowingPetsForShelter"] = "Mostrando pets para o abrigo ID:",
            ["OurMission"] = "Nossa missão",
            ["MissionDescription"] = "Todo animal merece um lugar seguro para chamar de lar. Trabalhamos com abrigos locais para oferecer cuidado e encontrar famílias definitivas, garantindo que cada cauda tenha um final feliz.",
            ["FooterBrandDescription"] = "Ajudamos pets a encontrar segurança, cuidado e lares amorosos por meio de abrigos, voluntários e apoio da comunidade.",
            ["Links"] = "Links",
            ["About"] = "Sobre",
            ["Pets"] = "Pets",
            ["ContactUs"] = "Fale conosco",
            ["Hours"] = "Seg - Sáb, 9:00 - 18:00",
            ["TermsAndConditions"] = "Termos e condições",
            ["TermsText"] = "Ao usar este site, você concorda em fornecer informações precisas, respeitar os procedimentos de adoção e usar nossos serviços com responsabilidade.",
            ["AllRightsReserved"] = "Todos os direitos reservados.",
            ["AboutPageTitle"] = "Sobre nós",
            ["AboutHeading"] = "Sobre a Pawsitive Friends",
            ["AboutText"] = "Somos uma organização sem fins lucrativos que fez parceria com abrigos em todo o mundo para chamar atenção aos animais que precisam de amor, cuidado e um lar para sempre. Nossa missão é conectar pessoas a abrigos e ajudar animais que esperam por uma segunda chance.",
            ["DonatePageTitle"] = "Doar | Pawsitive Friends",
            ["SupportOurMission"] = "Apoie nossa missão",
            ["DonateHeading"] = "Ajude-nos a cuidar de mais pets.",
            ["KindlyContactUsOn"] = "Entre em contato conosco em",
            ["OrFillFormContact"] = "Ou preencha o formulário para que possamos entrar em contato com você.",
            ["DonateSuccess"] = "Entraremos em contato assim que recebermos seus dados.",
            ["FirstName"] = "Primeiro nome",
            ["LastName"] = "Sobrenome",
            ["Country"] = "País",
            ["SelectCountry"] = "Selecione um país",
            ["PhoneNumber"] = "Número de telefone",
            ["Email"] = "E-mail",
            ["Submit"] = "Enviar",
            ["ReachUsThrough"] = "Ou fale conosco por:",
            ["VolunteerPageTitle"] = "Junte-se à nossa equipe de voluntários",
            ["JoinTheCrew"] = "Junte-se à equipe",
            ["VolunteerHeading"] = "Compartilhe seu tempo, cuidado e energia com pets resgatados.",
            ["VolunteerLead"] = "Seja voluntário conosco e ajude a criar dias mais seguros e felizes para pets que esperam um lar.",
            ["VolunteerSupport"] = "Preencha o formulário e nossa equipe entrará em contato com os próximos passos.",
            ["VolunteerSuccess"] = "Obrigado pelo seu interesse em ser voluntário. Entraremos em contato assim que recebermos seus dados.",
            ["SubmitApplication"] = "Enviar candidatura",
            ["SigninHeading"] = "Entrar",
            ["SigninText"] = "Entre para ajudar seu amigo da Pawsitive!",
            ["ContinueWithGoogle"] = "Continuar com Google",
            ["ApplicationPageTitle"] = "Solicitação para pet",
            ["PetApplication"] = "Solicitação para pet",
            ["PersonalInformation"] = "Informações pessoais",
            ["FullName"] = "Nome completo",
            ["Address"] = "Endereço",
            ["HowWouldYouLikeToHelp"] = "Como você gostaria de ajudar?",
            ["Foster"] = "Acolher",
            ["Sponsor"] = "Patrocinar",
            ["AdoptionQuestions"] = "Perguntas sobre adoção",
            ["DoYouOwnOrRent"] = "Você possui ou aluga?",
            ["DoYouHaveOtherPets"] = "Você tem outros pets?",
            ["WhyDoYouWantToAdopt"] = "Por que você quer adotar?",
            ["FosterQuestions"] = "Perguntas sobre acolhimento",
            ["HowLongCanYouFoster"] = "Por quanto tempo você pode acolher?",
            ["ExperienceWithAnimals"] = "Experiência com animais?",
            ["SponsorshipQuestions"] = "Perguntas sobre patrocínio",
            ["MonthlyContribution"] = "Contribuição mensal",
            ["WhyDoYouWantToSponsor"] = "Por que você quer patrocinar?",
            ["ConfirmAccurate"] = "Confirmo que todas as informações são precisas",
            ["NoPetNameProvided"] = "Nenhum nome de pet fornecido",
            ["FindNearestShelter"] = "ENCONTRE O ABRIGO MAIS PRÓXIMO",
            ["ChooseLocation"] = "-- Escolha um local --",
            ["SeeAllPets"] = "Ver todos os pets",
            ["SelectAShelter"] = "Selecione um abrigo",
            ["GoToShelter"] = "Ir para {0}",
            ["PetsPageTitle"] = "Pets",
            ["All"] = "Todos",
            ["NoPetsInCategory"] = "Nenhum pet encontrado nesta categoria.",
            ["Age"] = "Idade",
            ["LessThanYearOld"] = "Menos de um ano",
            ["YearOld"] = "{0} ano",
            ["YearsOld"] = "{0} anos",
            ["Breed"] = "Raça",
            ["Energy"] = "Energia",
            ["Description"] = "Descrição",
            ["HelpPet"] = "Ajudar {0}",
            ["ThankYouPageTitle"] = "Obrigado {0}",
            ["ThankYou"] = "Obrigado!",
            ["ApplicationNotFound"] = "Não conseguimos encontrar sua solicitação.",
            ["ThankYouName"] = "Obrigado, {0}!",
            ["ApplicationReceived"] = "Recebemos com sucesso sua solicitação para {0}. Vamos analisar sua solicitação e entrar em contato com você em 7 a 10 dias úteis.",
            ["ApplicationId"] = "ID da solicitação",
            ["Submitted"] = "Enviado",
            ["ReturnHome"] = "Voltar ao início",
            ["NotFound"] = "Não encontrado",
            ["NotFoundText"] = "Desculpe, o conteúdo que você procura não existe."
        }
    };

    public event Action? LanguageChanged;

    public string CurrentLanguage { get; private set; } = "English";

    public string this[string key]
    {
        get
        {
            if (translations.TryGetValue(CurrentLanguage, out var lang) && lang.TryGetValue(key, out var value))
            {
                return value;
            }

            if (translations["English"].TryGetValue(key, out var fallback))
            {
                return fallback;
            }

            return key;
        }
    }

    public void SetLanguage(string language)
    {
        if (!translations.ContainsKey(language) || language == CurrentLanguage)
        {
            return;
        }

        CurrentLanguage = language;
        LanguageChanged?.Invoke();
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(this[key], args);
    }
}
